# Generated by Django 6.0 on 2025-12-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RightHandCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('toyota', 'Toyota'), ('nissan', 'Nissan'), ('subaru', 'Subaru'), ('mitsubishi', 'Mitsubishi'), ('honda', 'Honda')], max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('generation', models.CharField(blank=True, max_length=30)),
                ('year_from', models.IntegerField()),
                ('year_to', models.IntegerField()),
                ('engine_volume', models.FloatField(help_text='в литрах')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель')], max_length=10)),
                ('fuel_consumption', models.FloatField(help_text='л/100км средний')),
            ],
        ),
    ]
