# Generated by Django 6.0.1 on 2026-01-08 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_ownershipcalculation_costitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='righthandcar',
            options={'ordering': ['brand', 'model', 'year_from'], 'verbose_name': 'Праворульный автомобиль', 'verbose_name_plural': 'Праворульные автомобили'},
        ),
        migrations.AddField(
            model_name='righthandcar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='righthandcar',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='righthandcar',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AddField(
            model_name='righthandcar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='righthandcar',
            name='brand',
            field=models.CharField(choices=[('toyota', 'Toyota'), ('nissan', 'Nissan'), ('subaru', 'Subaru'), ('mitsubishi', 'Mitsubishi'), ('honda', 'Honda')], max_length=20, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='righthandcar',
            name='engine_volume',
            field=models.FloatField(help_text='в литрах', verbose_name='Объем двигателя'),
        ),
        migrations.AlterField(
            model_name='righthandcar',
            name='fuel_consumption',
            field=models.FloatField(help_text='л/100км средний', verbose_name='Расход топлива'),
        ),
        migrations.AlterField(
            model_name='righthandcar',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель')], max_length=10, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='righthandcar',
            name='generation',
            field=models.CharField(blank=True, max_length=30, verbose_name='Поколение'),
        ),
        migrations.AlterField(
            model_name='righthandcar',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='righthandcar',
            name='year_from',
            field=models.IntegerField(verbose_name='Год выпуска с'),
        ),
        migrations.AlterField(
            model_name='righthandcar',
            name='year_to',
            field=models.IntegerField(verbose_name='Год выпуска по'),
        ),
    ]
