# Generated by Django 6.0.1 on 2026-01-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_righthandcar_options_righthandcar_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='righthandcar',
            name='image_url',
            field=models.URLField(blank=True, help_text='Ссылка на фото автомобиля (рекомендуется 400x250px)', max_length=500, null=True, verbose_name='URL изображения'),
        ),
    ]
