# Generated by Django 6.0 on 2026-01-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_righthandcar_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownershipcalculation',
            name='adaptation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Адаптация'),
        ),
        migrations.AddField(
            model_name='ownershipcalculation',
            name='customs_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Таможня'),
        ),
        migrations.AddField(
            model_name='ownershipcalculation',
            name='fuel_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Топливо'),
        ),
        migrations.AddField(
            model_name='ownershipcalculation',
            name='insurance_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Страховка'),
        ),
        migrations.AddField(
            model_name='ownershipcalculation',
            name='maintenance_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ТО и ремонты'),
        ),
        migrations.AddField(
            model_name='ownershipcalculation',
            name='tax_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Транспортный налог'),
        ),
        migrations.AddField(
            model_name='ownershipcalculation',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Итоговая стоимость'),
        ),
    ]
