# Generated by Django 6.0 on 2026-01-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_ownershipcalculation_adaptation_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownershipcalculation',
            name='additional_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Дополнительные расходы'),
        ),
        migrations.AlterField(
            model_name='ownershipcalculation',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Полная стоимость владения'),
        ),
    ]
